### ISSUE TITLE
客户端心跳检测

### ISSUE THREAD

**Issue by kenan2002** [bearyinnovative/bearychat-rtm-client#5]
客户端发出心跳后，计时一定时间后主动断开重连

**Comment by oHaiyang** [comment]
是指：“心跳一直不返回的话，就断开链接，然后重连” 吗？

**Comment by kenan2002** [comment]
就是心跳检测，一定时间之内没受到任何东西就断开重连

**Comment by kenan2002** [comment]
> 所以 Client 发起 closure 后，会等待 Server 端来 close the TCP connection

这里在主动关闭的时候其实完全可以不等上一个连接断开，直接开始下一次连接吧

**Comment by oHaiyang** [comment]
> 这里在主动关闭的时候其实完全可以不等上一个连接断开，直接开始下一次连接吧

嗯，我就是这个意思，增加一个 fastly close 的机制，直接让 rtm-client 到 `closed` 状态。

**Comment by oHaiyang** [comment]
done with #10 and optimized with #15
